/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 asper.glb -T 
Files: asper.glb [4.94MB] > C:\Users\sumit\OneDrive\文档\project\ASPER\asper-landing\public\models\asper-transformed.glb [185.16KB] (96%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function AsperLogo(props) {
  const { nodes, materials } = useGLTF('/models/asper-transformed.glb')
  return (
    <group {...props} dispose={null}>
<mesh
  geometry={nodes.Mesh10.geometry}
  material={materials.BakedMaterial}
   material-metalness={0.9}
  material-roughness={0.12}
/>
    </group>
  )
}

useGLTF.preload('models/asper-transformed.glb')
